### ISSUE TITLE
Go to replies when they're clicked

### ISSUE THREAD

**Issue by phoebe-leong** [MathMan05/JankClient#12]
It would be good to to be able to navigate to the message being replied to by clicking the message that shows up above the reply, indicating which message is being replied to. I hope this makes sense.

**Comment by MathMan05** [comment]
I understand what you're saying, but depending if the reply exists on screen, it'll add some complexities

**Comment by phoebe-leong** [comment]
Ah yeah that's true. I know Discord has the ability to do it, I don't know how though. It's not an important feature really, just a QOL that could be looked into further down in development.
Thanks for the input :)

**Comment by MathMan05** [comment]
I know how-ish to do it, it's just doing it that's the hard part

**Comment by MathMan05** [comment]
don't know why it closed

**Comment by MathMan05** [comment]
this has been done
