### ISSUE TITLE
Not loading a default theme

### ISSUE THREAD

**Issue by phoebe-leong** [MathMan05/JankClient#18]
I just downloaded and tested the Typescript port to try to figure out a seperate issue. But when I loaded it up, I noticed it looked really weird.

I went to settings and selected a theme (the theme selector just showed nothing) and from then on it worked.

<img width="1440" alt="Screenshot 2024-06-30 at 2 28 53 am" src="https://github.com/MathMan05/JankClient/assets/65205197/93dd9d5e-198f-4521-854d-a90f0ad49c8a" alt="themes not loadin">

It works fine when you aren't logged in, since it redirects to the login page which presumably sets a default theme.

Hm. Can't recreate it.

**Comment by MathMan05** [comment]
huh, I'll have to look into this

**Comment by MathMan05** [comment]
Oh, I think I know what it is

**Comment by MathMan05** [comment]
fixed with
https://github.com/MathMan05/JankClient/commit/96b2dbb21c8e88e19ebe9b931f5c83418ce36091
