### ISSUE TITLE
If a message has been edited, display that and the date/time on hover

### ISSUE THREAD

**Issue by MathMan05** [MathMan05/JankClient#2]

**Comment by MathMan05** [comment]
Not entirely sure if I get edit dates/times outside of the main date, I'll look into it, but until I confirm that getting the edit date/times is possible, I won't be moving this from the requests category.

**Comment by DEVTomatoCake** [comment]
There's an `edited_timestamp` property on every message, if it's edited, it contains the timestamp (e.g. `"2024-06-09T18:58:49.000+00:00"`), otherwise it's `null`.
