### ISSUE TITLE
Consistent casing of Context Menu entries (e.g. "edit"/"copy" vs. "Delete"/"Mark")

### ISSUE THREAD

**Issue by MathMan05** [MathMan05/JankClient#3]

**Comment by MathMan05** [comment]
Not quite sure what this means, can I get some more info

**Comment by DEVTomatoCake** [comment]
![Image](https://github.com/MathMan05/JankClient/assets/60300461/254c56fc-f1a7-4d6b-8982-4107da30e769)

**Comment by MathMan05** [comment]
Oh, I see, that is totally my fault lol
