### ISSUE TITLE
Allow the "Save changes" popup in settings to appear multiple times. Doesn't work in Theme settings when changing accent color.

### ISSUE THREAD

**Issue by MathMan05** [MathMan05/JankClient#44]

**Comment by MathMan05** [comment]
@DEVTomatoCake it was fixed in https://github.com/MathMan05/JankClient/commit/8c39561906465469e564078779ca80c74dedb60b

**Comment by DEVTomatoCake** [comment]
Bad timing lol, thanks

**Comment by MathMan05** [comment]
it's ok, dw, the issue was still appreciated
