### ISSUE TITLE
"Copy user ID" context menu for users/members

### ISSUE THREAD

**Issue by MathMan05** [MathMan05/JankClient#6]

**Comment by MathMan05** [comment]
Sorry for not turning this into an issue earlier, but do you mean like right clicking the dms and getting the user id or?

**Comment by DEVTomatoCake** [comment]
Both actually, right click on DM allows copying the user & channel ID, and right clicking a profile on a server or DM opens a new context menu with the option to copy the ID. The latter would make the "Copy user ID" in the message context menu useless.

**Comment by MathMan05** [comment]
finally get a menu for DMs
