### ISSUE TITLE
Translation issue with message Wikimedia:Jank-client-permissions.descriptions.USE SOUNDBOARD/fr

### ISSUE THREAD

**Issue by Mahabarata** [MathMan05/JankClient#79]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-permissions.descriptions.USE_SOUNDBOARD&group=jank-client&language=fr

In french, "soundboard" can be translated in different ways.

Could you describe this feature?

**Comment by MathMan05** [comment]
soundboard like the discord soundboard

**Comment by Mahabarata** [comment]
Ok, so it looks like the name of a "device". On discord manual, this name is not translated but maybe we can: have you used this word somewhere else that is not on translatewiki?

Another problem if soundboard is a device: in this message URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-permissions.descriptions.MANAGE_GUILD_EXPRESSIONS&group=jank-client&language=fr it doesnt fit because of the plural.

In some other messages we find "soundboard sounds": maybe better in this last message? (or remove the s?)

**Comment by MathMan05** [comment]
I don't really know if this is incorrect or not, I'll have to ask someone else

**Comment by MathMan05** [comment]
I have now asked and have corrected it.

**Comment by Mahabarata** [comment]
Ok, thanks.
