### ISSUE TITLE
Translation issue with message Wikimedia:Jank-client-typing/fr

### ISSUE THREAD

**Issue by Mahabarata** [MathMan05/JankClient#81]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-typing&group=jank-client&language=fr

Could you add a documentation for this message?
In particular, what is/are the type/values of $1 and $2?

**Comment by MathMan05** [comment]
I've went ahead and added documentation to this message in qqq.json

**Comment by Mahabarata** [comment]
Thanks
