### ISSUE TITLE
Translation issue with message Wikimedia:Jank-client-guild.disoveryTitle/fr

### ISSUE THREAD

**Issue by Mahabarata** [MathMan05/JankClient#82]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-guild.disoveryTitle&group=jank-client&language=fr

Source text is "Guild discovery ($1) {{PLURAL:$1|entry|entries}}".

Do you mean "Guild discovery ($1 {{PLURAL:$1|entry|entries}})" (closing parenthesis moved to end)?

$1 is the number of guilds?

A documentation will help.

**Comment by MathMan05** [comment]
I'm adding documentation, and you are correct that's weirdly formatted, I'll correct it
