### ISSUE TITLE
Translation issue with message Wikimedia:Jank-client-role.delete/fr

### ISSUE THREAD

**Issue by Mahabarata** [MathMan05/JankClient#83]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-role.delete&group=jank-client&language=fr

What is the difference between delete role and remove role?

Can these messages be visible at the same time (same section, list, etc)?

**Comment by MathMan05** [comment]
Deleting a role deletes it, but removing it removes it from the current context, for example you may remove a role from a channel that's overriding permisions, but you also might delete a role from the guild as a whole, removing it everywhere.
