### ISSUE TITLE
Translation issue with message Wikimedia:Jank-client-localuser.VoiceWarning/fr

### ISSUE THREAD

**Issue by Mahabarata** [MathMan05/JankClient#84]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=jank-client-localuser.VoiceWarning&group=jank-client&language=fr

There is no question mark in this message. Maybe instead of the first comma?

**Comment by MathMan05** [comment]
thank you for catching my dumb phrasing, I've corrected it
